"""Rating migration

Revision ID: ca5c5997e77c
Revises: ea309eeff9ac
Create Date: 2025-01-21 21:25:20.485199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5c5997e77c'
down_revision: Union[str, None] = 'ea309eeff9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('rating', sa.Float(), nullable=True))
    op.drop_column('product', 'raiting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('raiting', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('product', 'rating')
    # ### end Alembic commands ###
